### ISSUE TITLE
Flag respawn timers

### ISSUE THREAD

**Issue by Nick-Riggs** [tagpro-game/tagpro-issues#1]
*Highly subject to change based on play testing*

## The problem

1. Regrab is becoming the only TagPro strategy because it's highly effective. This leads to the flags being out the majority of the match.

2. This problem is amplified on medium to large maps, as defense has no chance to return to base after a chase to contain a regrab. This results in "chasey" maps. I believe this is the core reason why larger maps are being retired and being replaced with small/tiny maps.

## Gameplay changes

Experiment with adding respawn timers to flags. This will make regrab more difficult, but still possible. It will also add some new gameplay excitement when trying to time a cap or grab based on a flag's re-spawn timer.

### How would it work?

1. The time it takes for a flag to return to it's base is based on the distance it is from the base.
2. The distance is based on pathing, not a straight line. The ensures chasers have a fair time-frame to work back towards the base, no matter what the map. 
3. The flag paths back to base in the case of carrier death or a cap. 
4. You can't cap while you flag is returning to base.
4. The flag will visually path back to base - you'll see it moving across the map. 
5. There will also be a timer on the UI to indicate when the flag will arrive home. 
6. The flag only treats walls and spikes as obstacles when returning. 
7. The speed of the flag is 6.6 tiles per second. Very close to the top speed of a player. 
8. Handoffs are still possible as the time scales. Respawns for returns near the base are very fast.

### Raise the death penalty

I think it's necessary to raise the respawn time of players from 3 seconds to 5 seconds. The reason is to combat a new strategy that I think will emerge: Suicide after returning the flag, will often be a better option for a chaser to get back into a defensive position than to race the returning flag home. In 5 seconds, the returning flag could cover roughly 34 tiles - rendering the suicide strategy less effective in more situations.

EDIT: I like steppin's idea better. After play testing it, I like it alot.

**Comment by JonathanDCohen** [comment]
>The flag will visually path back to base - you'll see it moving across the map.

Will you be able to catch it?  Could be confusing if you see the flag pathing back to base and go for it, but it goes right through you.  On the other hand, it would make offensive defense nearly impossible since the whole team will be crowding around trying to put the block on and so there will be a good chance of the flag just randomly landing back in the other team's hands.

**Comment by AMorporkian** [comment]
No catching. The flag is transparent; it makes it pretty obvious that you can't pick it up.

**Comment by tagprowreckn** [comment]
Okay, I have a long response and a short response.  This is the long response.


Regrab adds strategy.  I really don't think that you need to add a new flag-timer mechanism to the game, because there are already ways to impair regrab, even on "chasey" maps.  In my opinion, knowing when to intermittently come off of regrab or how to fight the opposing regrabber in order to make a scoring attempt is what separates the TRUELY good teams from the rest.  

What *would* help, however, is **to facilitate the coordinated activity between teammmates across large distances.** In other words, add a mini map or something similar so that any player can instantly see what his teammates see.  This is really a third form of communication, in addition to voice chat and macros.  Focused map design can help out here, too.  Let me expound upon this thesis.

First, think about what players can do on maps that are known to be chasey.  Consider the chasiest map of them all, the Holy See.  It's easy to run around on this map, but it's also easy to find a powerup, which is fortunate, because **power-ups help to defeat the regrab.**  Here are several distinct examples of how powerups can help defeat the regrab, assuming both flags are out on the map:

1.  A **rolling bomb** will give a flag carrier a three-second window to cap if he is next to his flag tile  This means that he will generally cap if he can expend his bomb right before his teammates make the return, **but this requires precise coordination.**  Of course, rolling bombs also prevent captures from happening, but as long as they aren't too numerous (i.e., there aren't 20 powerups on the field), then rolling bombs will generate chances to score.

2.  A **tagpro** gives the opportunity for a non-flag carrier to escort his flag carrier home.  Obviously this means you are getting off regrab, which is akin to pulling the goalie in hockey, but it's sometimes necessary when you are down a point and there isn't much time left.  The problem is that it's **hard to coordinate this** using voice chat.  Note that the Tears 4 Spheres kept a tagpro on regrab in the season 6 MLTP finals when they were in this exact situation, and they lost.  Note that you can escort without the TagPro, but in the situation where both the Escort and the Regrabber have a TagPro, and mutually pop, the Escort is successful in his objective.  Furthermore, the escort can deal with a double or even a triple regrab if he has a Tagpro.

3.  Finally, while it doesn't necessarily require a powerup, **strategic kissing** is a tactic that can be employed.  You turn your flag-carrier into a flag-chaser, while putting another ball at home to combat the regrab.  This is somewhat of a less risky way of coming back into the game than an escort, because you haven't abandoned regrab yourself, but you are putting your own flag carrier in danger.  You can also strategically kiss if your flag carrier picks up a TagPro, or if your Regrabber picks up a rolling bomb, because these kisses give your team the advantage.  **Everything listed under point number 3 requires sub-second coordination,** which is quite hard to achieve using mumble, but is quite apparent when you can see all of your teammates at once.


Now, think about how map designers can incorporate elements or techniques into large maps that can help combat the evil regrab demon.  You are correct when you say that maps are shrinking in an effort to lower the average flag hold time.  I think that part of the reason for this is due to the way the map committee is established: if you have a committee that selects maps on a democratic basis, then you're going to try to address an issue in the most seemingly apparent way possible, even if there might be other ways that are also correct but perhaps not so obvious, and especially when the members of the committee are picked based on how well they can kibbutz and how quickly they can come up with an snappy opinion.  You're also going to get more average-looking maps.  Anyway, enough of that.    Here's how you can reduce regrab effectiveness in a large map:

**1.  Reduce the number of islands.**  By "islands," I mean the number of clusters of impassable elements (spikes, walls, green gates) that are not adjacent to the outer walls of the map.  *Simplicity*, by BBQChicken, isn't a particularly large map by area, but it is still quite difficult to return the flag because of all the spike islands.  Even wormy can be fairly chasey.

**2.  Make the map more linear.**   The regrab is particularly strong on maps like Blast Off, Holy See, and Pokeball because the regrabbing player has a shorter path to his base than the chasers do if they make the return in the corner of the map.  Thus, even if you make a return, it often doesn't matter because the guy who made the regrab has great field position within a matter of seconds.  In contrast, on a tubular map with a lot of islands (like Boombox), it's easy enough to run around and have a free regrab, but if the defenders make a return, the player wh3.  Give the flag carrier some method of impairing the regrab.  This is most easily done with bombs, which can be triggered right before the o made the regrab is almost always in a worse field position than was the guy who lost the flag.   This principle would hold true even if Boombox was 1000 tiles long; as long as there is only one lane between the bases, then the chasers always gain ground when they make the return.

**3.  Give the flag carrier some method of impairing the regrab.**  This is most easily done with bombs, which can be triggered right before the return is made, **but this requires precise coordination.**  Alternatively, the flag carrier can sit on a button that forces the regrabbing player to take a longer route out of the base.

**4.  Add more elements that FC's can use around the base.**  This is more of an extention of point 3 above, but any element that can move a regrabber off of the flag tile (like a fan, a spike that moves over the flag tile, etc) that the FC can toggle around the base will impair regrab.
