### ISSUE TITLE
Issue #108 happened again

### ISSUE THREAD

**Issue by goodluckhavefun123** [tagpro-game/tagpro-issues#115]
Please help.

![screen shot 2015-01-22 at 10 34 53 pm](https://cloud.githubusercontent.com/assets/10569709/5869427/0a7d0770-a287-11e4-8f7b-da5fdd7dcfbc.png)

**Comment by goodluckhavefun123** [comment]
![screen shot 2015-01-22 at 11 24 59 pm](https://cloud.githubusercontent.com/assets/10569709/5869819/03c4bdae-a28e-11e4-9efa-9d2560df6cd2.png)

**Comment by banzaiTP** [comment]
Yea, this happens to me frequently. I assumed I was just not understanding some new change to the rank points system. I haven't tracked it, but I'd guess I'm encountering it in 10% of my games--and that's a conservative estimate. First I thought it was in games that start 2-1 or that sort of thing. But I've had a few games where I entered at the start with one other guy, and that guy got points and I didn't. (And re: the contribution thing, I'm above him on the scoreboard.) Or I've had several games where the losing team gets points and the winning team doesn't, even in even 4 on 4 games.

I happened to take this screenshot yesterday (Thursday, 1/22)
![screen shot 2015-01-22 at 3 38 14 pm](https://cloud.githubusercontent.com/assets/10677440/5884245/10065c9e-a329-11e4-8059-faa0bd563593.png)


And this one today:

![screen shot 2015-01-23 at 5 22 25 pm](https://cloud.githubusercontent.com/assets/10677440/5884254/2aa93896-a329-11e4-974c-2a73983a1897.png)

**Comment by NewCompte** [comment]
Are you sure this is a new issue ?

I see nothing in the code that may have changed that in the past few weeks, but I definitely see a lot of those complaints now and none before.

**Comment by goodluckhavefun123** [comment]
Yes, I am sure this is a new issue.

**Comment by goodluckhavefun123** [comment]
And Again:

![screen shot 2015-01-24 at 1 44 20 am](https://cloud.githubusercontent.com/assets/10569709/5886398/9005e6a8-a36a-11e4-8b81-5e9970400beb.png)

**Comment by banzaiTP** [comment]
Hey gl hf, I think the last one you're mistaken. Someone had changed their name to match yours. But you actually appear to have received 21 points in that game. Sorry to call you out lol, but I wanted to point that out to clarify that THAT particular time may not have been indicative of "the bug," but the other reports are legit. (I didn't want someone seeing that this was a mistake at your end and assuming the others were as well.)

For what it's worth, strangely, I didn't notice it happening in a few hours worth of games tonight. (I may have seen it once or twice, but not much.)

I don't know anything about this stuff, so if I'm way off here, forgive me. Just sort of asking questions based on my own experiences. Did something change in regards to games that start with uneven teams? Tonight I was playing in what I would imagine to be "prime hours" (late night on a Friday into Saturday), so while I didn't keep track, I would imagine I didn't run into many less-than-full games. I could be mistaken, but it seems like I ran into the issue more often during the day, when I would imagine more games start unevenly.

(But, again, even if something was intentionally changed, things appear to be a bit "off," because I've played games where I was in from the start and received the "-" for rank points while teammates did get credit.)

And finally, to directly respond to newcompte, this definitely seems new. I didn't see any complaints about this issue before I started noticing it myself recently. So I really don't think it's the type of thing where it existed all along, somebody pointed it out, and now I keep noticing it. As I think I mentioned, it was happening frequently enough that I just assumed some rank point formula change had been made that I didn't understand. When I realized some of the scores didn't seem to make any sense at all, I went looking to see if others had reported it.

**Comment by goodluckhavefun123** [comment]
Sorry, You are right. The last one was not an example. I'll delete it from the thread.

**Comment by I-mess-up** [comment]
A player played most of the game and scored a cap yet earned no rank points:
![image](https://cloud.githubusercontent.com/assets/10187488/5888969/b8aac130-a3c6-11e4-9e3a-7ccc43f13638.png)

**Comment by banzaiTP** [comment]
Hello, i-mess-up. I'm a little worried about muddying the waters here. Are you sure their stats were on and stuff? There's no check mark. I'm not disputing what you're saying, just trying to provide the devs with obvious, concrete examples. (Like in my second example above you can see three players on the winning team with 45+ rank points and check marks next to their name receiving nothing while players on the losing team got credit.)

Though as I mentioned before, I didn't notice it last night, and through 14 games today it definitely hasn't happened. Was the process of implementing something for next weekend going on over the previous 10 days and then finished yesterday or something? I'm clueless about this stuff, so obviously I have absolutely no idea why it happened. But an unknown bug would be even stranger if it just completely "fixed" itself, right?

**Comment by I-mess-up** [comment]
OK, maybe mine was incorrect. Pay attention to glhf’s screenshots.




But I won’t remove it just yet in case it turns out my screenshot was an actual bug.

**Comment by banzaiTP** [comment]
Oh, i-mess-up, just to clarify--I have no official role in any of this. I've just also been encountering it/reporting it as a player and so checking back on this thread. So I know it's a real thing. 

I was just worried about people possibly looking at something like yours and thinking, "guy wasn't logged in" and assuming that was the explanation for all the reports. There are definitely unambiguous examples of "something wrong," so I didn't want to distract from those. Hope that makes sense :-)

**Comment by goodluckhavefun123** [comment]
And again

![screen shot 2015-01-26 at 9 56 44 pm](https://cloud.githubusercontent.com/assets/10569709/5912742/75db43a2-a5a6-11e4-9aea-0fe4cf51e610.png)

**Comment by NewCompte** [comment]
I can see in the code why your teammates got rank points and you didn't. This issue doesn't seem to be new.

In this case, none of you should have got rank points because of the opponents being terrible.

**Comment by goodluckhavefun123** [comment]
Ok, but what about the other examples? And what would cause my teammates to get rank points  without me getting any?

**Comment by NewCompte** [comment]
I don't remember in which order players joined in the previous examples and I can't check it.

In your latest example, the fact that you joined after the opposite team made the game not realize yet that the opponents were terrible the first time it checked and the shortness of the game made that check be the only check.

I will make some code that will check whether the opponents are terrible on a team-level and not on a player level.

**Comment by I-mess-up** [comment]
From Reddit:
"Im starting to get really frustrated with this system as it seems completely arbitrary. Ive had a couple of games this morning where it would be 4v4 for 2 minutes and I would be the only one playing/not afk/doing something productive on my side and I would end up being the only one on my team whom the loss counts for. On the other side ive had games go 4v4 for well over 2-3 minutes where everyone is playing and the W doesnt count. The system just doesnt seem to make any sense at all, like i get it for games that you're in for less than 30 seconds etc but there seems to be some major flaws."

http://www.reddit.com/r/TagPro/comments/2tuhx6/can_someone_explain_the_system_for_games_counting/

**Comment by banzaiTP** [comment]
NewCompte, what about something like my second example? My team won 3-0 in a game that lasted 2+ minutes. Games that end 3-0 after 2 minutes and change is not the norm, obviously, but it's certainly not highly unusual. And yet only the losing team got rank points. 

Again, I don't understand coding stuff. But it seems to me like it could make sense if the game decided everybody was terrible and so nobody on either team got points. That seems like it would be an "acceptable" error or something. But ONLY the losers getting points? Surely a system that would do that is flawed, right?

**Comment by NewCompte** [comment]
Your team's opponents were thought terrible by the game, their teams opponents weren't.

Obviously there is some room for change on this issue as this game behavior was made around March 2013, when the game was <2 months old..

**Comment by goodluckhavefun123** [comment]
That makes sense. However, I think even if your team's opponents are terrible and you do really well, you should get the same, if not more, points than if your teams opponents are excellent  and you do horribly.

**Comment by banzaiTP** [comment]
Thanks for the response, but I'm now super confused. I'm as sure as a person can be that this simply did not happen previously. The only thing I ever noticed was that people would not get any rank points if the game was too brief. I never encountered not getting rank points/ not having a win count for me because my opponents were terrible.

**Comment by Nick-Riggs** [comment]
In the case of complete blow outs, it's possible for the game to decide you weren't playing actual opponents. This is to protect against game stacking - the act of a person filling a game with fake players on an empty server to farm ranking stats. From time to time, it does result in false positives. 

The algorithm could be tweaked or improved, but it's essentially working as intended - and has been for nearly a year.

**Comment by goodluckhavefun123** [comment]
Thank you for the clarification.

**Comment by banzaiTP** [comment]
But why do some people get credit while others don't?!?! I just played a game. It started 4 on 4. Then a bunch of red players quit. This is the final scoreboard. I'm sorry, but something is definitely operating differently from before. This did not used to happen. Did changing the dc rules somehow accidentally throw off the other algorithm since it used to be based on >30 second games or something?

![screen shot 2015-01-28 at 1 33 51 am](https://cloud.githubusercontent.com/assets/10677440/5933417/12b364b0-a68e-11e4-87b7-69a49004c4c9.png)
