### ISSUE TITLE
Powerups are picked up if ball is already on it

### ISSUE THREAD

**Issue by AMorporkian** [tagpro-game/tagpro-issues#13]
If the ball is on the powerup when it spawns, it is picked up. Similar to flags. Current behavior is the ball needs to move off the powerup to pick it up.

**Comment by Nick-Riggs** [comment]
I've marked this as something we'll change. Does anyone strongly disagree?

**Comment by steppin** [comment]
I think during a previous meeting we decided we should at least play test this, so I agree

**Comment by I-mess-up** [comment]
What would happen if two balls are on it, as will frequently happen in MLTP?

**Comment by SomeBall-1** [comment]
Will boosts and bombs' behavior also change? I could see it working for bombs, not sure how boosts could be handled because momentum is required (nothing happens while on top of it motionless but the slightest bit of movement will set it off?) but I think if you're changing powerups then there should be consistency with other map elements. Similarly, buttons that set off bombs would also go off if you're sitting on the button when the bomb spawns.

**Comment by Nick-Riggs** [comment]
@I-mess-up Closest would win. 

@SomeBall-1 I'm personally for it working with bombs and boosts. 

In the case of boosts, if you are completely motionless when it spawns I guess we do nothing - but that would be really really rare.

**Comment by Snorge** [comment]
@Nick-Riggs @AMorporkian 

Any updates? When I read this thread several weeks ago I was hoping it would be coming soon.
