### ISSUE TITLE
[Suggestion] Gates/Walls Only Non-Flagcarriers Can Pass Through

### ISSUE THREAD

**Issue by DaEvil1** [tagpro-game/tagpro-issues#136]
I'm not sure if the proper terminology would be "wall" or "gate" for this, but the principle is as following:

Have a tile that will either stop a flagcarrier like a wall, or kill the flagcarrier if they attempt to pass through it. This would open up a lot more options for mapmakers experimenting with different designs such as new basedesign, mechanics for a team to catch up, and closing off potential turtlespots for an fc that have other uses for non-fcs.

I really think this would be a simple and intuitive addition, that would add so much depth to map-designs and open up for a whole other level of matches both in PUBs and in the leagues, and TagPro overall would greatly benefit from this.

**Comment by DaEvil1** [comment]
THIS HAS BEEN LABELLED

**Comment by ylambda** [comment]
I discussed some of this idea with @DaEvil1 on mumble. I agree it adds more options/flexibility for maps. My only concern is how to represent this tile to the player.

I had the thought of using normal floor tiles, and when a player grabs the flag, the impassable wall/gate will appear. I'm backing away from this idea, because I think it is also confusing. Non-flags carriers would be wondering where the impassable tiles are.

In addition, I think other suggestions like diagonal gates should take a priority over this.

**Comment by tagprowreckn** [comment]
It's a great idea for a tile, and if TagPro could use anything, it's more map elements (a lot more).  But Lambda raises a good point, because it's hard to represent this element as a concrete "thing," and it's better to represent an element with a concrete picture like a bomb or a spike as opposed to an abstract image like a colored tile.  (As an added bonus, the more things that are represented by concrete things, the easier it is for commentators to make jokes during broadcasts.)


Here's my idea: a clothesline.  Balls can run under the clothesline, but because the flag is carried on top of the ball, the clothesline will knock the flag off the ball and on to the ground, at which point the flag would quickly fade into nothingness while simultaneously and instantly reappearing in the base.  The flag carrier wouldn't die if he hit the clothesline, but he would be penalized with a drop.  

Unlike other elements, this element would not be totally tile based.  The clothesline would be supported by two posts, which are solid blocks that act like walls. The clothesline itself would be a line segment that extends from post to post.

You'd need an animation to represent this, but that shouldn't be too hard to make... pixi.js has ropes that could help to sell the clothesline effect.  (Bonus points if you can hang socks and polka-dotted underwear on the clotheline as well).

**Comment by jufda** [comment]
Sounds too complicated to me (if I understood it correctly), I think we should keep the game simple and fast to learn (and slow to master). Even now, it looks like the game is slowly going to little-harder-to-approach way, and every now and then I see new some balls in game having no idea what to do, especially with neutral flag maps, power-ups and gates. I don't think there should be objects that appear after game starts (idea of spawning the wall/gate when flag is grabbed).

"a tile that will either stop a flagcarrier like a wall, or kill the flagcarrier if they attempt to pass through it"
Is the chance random or what? There are gates, spikes and walls already, and I think I'm missing something here.

**Comment by DaEvil1** [comment]
No, not random. I was just not sure if killing fcs passing through or simply stopping them would be the best way. a way to illustrate what I actually mean can be found here: http://puu.sh/gRG2V/8971a91c36.png

On the left the red ball is not carrying a flag, and is allowed to pass through the wall. On the right, the red ball is carrying a flag and is not allowed through the wall. Obviously the visuals would be different, but this is to give a rough idea.

**Comment by jufda** [comment]
That image was worth a thousand words. I'd favour the wall version.
