### ISSUE TITLE
[Suggestion] Ultimate Game Saver flair

### ISSUE THREAD

**Issue by RondingTagPro** [tagpro-game/tagpro-issues#188]
As an awesome addition to the new [save statistic](https://www.reddit.com/r/TagPro/comments/309m6d/in_test_win_flair_rolling_300_stat_timeframe/), I hereby propose the Ultimate Game Saver flair.

The *Ultimate Game Saver flair* looks like a floppy disk and is stackable.

You get the Ultimate Game Saver flair when:
* your team is 0-2 behind when you join;
* your team is not carrying a flag when you join;
* the enemy team is carrying a flag when you join;
* nobody else joins your team after you joined;
* your team eventually wins 3-2.

**Comment by jufda** [comment]
Wouldn't in be even better if you are still 3vs4 after you join (otherwise similar)? I'm not a fan of the whole idea, because it's not a flair you can get with skill only (like 50/60/70% flairs, or some of the special events) or by just playing a lot (degree flairs). Those are the two ways that should be the only two ways to get flairs. Ultimate Game Saver flair requires conditions that are pretty rare, and require too much luck.

**Comment by RondingTagPro** [comment]
Of course you may fine-tune the conditions for awarding the flair. Getting the flair requires playing a lot, skill and luck, but I assume it will not take too long for long-term players to earn the flair - the probability of the conditions being satisfied is not actually that small. Like the St. Patrick day flair, eventually all frequent players will get it.
