### ISSUE TITLE
[Bug] Launching from a private group occasionally sends players to pubs

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#226]
It's happened to me, others in my group, and others in Reddit: http://www.reddit.com/r/TagPro/comments/37erkj/joining_pubs_from_private_group/

For some strange reason, launching from a group could cause one or more players to join a public game rather than the new private game.

**Comment by NewCompte** [comment]
Have you tried without userscripts/extensions ?

**Comment by wrigsam** [comment]
This is also happening to me. It only happens once every 10-20 games, so it's hard to rule out specific variables.

The joiner process is no different from when I join the private game. I just happen to go to a pub when everyone else goes to the private.

Then, when I leave and try to re-enter the group, it says I can't because it's private.

**Comment by NewCompte** [comment]
"Then, when I leave and try to re-enter the group, it says I can't because it's private."

You mean the game right ?

**Comment by NewCompte** [comment]
Activation fixed his issue (http://www.reddit.com/r/TagPro/comments/372tnx/unable_to_play_in_a_private_group/) by removing all userscripts.

**Comment by RonSpawnson** [comment]
Sounds like a userscript issue. Closing the issue

**Comment by port05** [comment]
@RonSpawnson @NewCompte I don't know if you already know this, but nabby's YAIS script was causing this issue. [This](https://gist.github.com/nabbynz/94926885ea020a832290) is the link to the most current version of the script that has fixed the issue.
