### ISSUE TITLE
Orientation period

### ISSUE THREAD

**Issue by AMorporkian** [tagpro-game/tagpro-issues#23]
Camera moves to spawn point instead of staying at location of death

**Comment by nrabins** [comment]
Sorry, I duplicated this with https://github.com/tagpro-game/tagpro-issues/issues/147.

The tweening idea is intriguing, but I'm not sure I like the idea of seeing areas of the map you haven't 'earned' (my same objection for having the camera stay on the spot of death for the full three seconds).

**Comment by jufda** [comment]
How about 1sec at the death point, fade out + fade in for total 1sec, 1sec at spawn point? Enough time to realize how you died, and just enough time to make fast decision about where to move when you spawn. I think it would also look cool, and it would be possible to add some kind of splatting effect / ball forming effect (from splats) instead of fading out and in.

**Comment by Nick-Riggs** [comment]
Marked as wont-fix for Classic but this is how Next will work.
