### ISSUE TITLE
[Suggestion] Fix some lag issues

### ISSUE THREAD

**Issue by ifactor1** [tagpro-game/tagpro-issues#260]
https://streamable.com/z1wf This is the result of a less than .1% overall packet loss. I was trying to stay north of the flag but glitched out right for a few seconds. I believe this is because events are sent when keys are pressed and released, and the release event is getting dropped by my connection.

I suggest updating which keys are currently pressed every event.

I'll eventually fix my lag, but this could potentially help others as well. The packet loss is not noticeable anywhere else.

**Comment by I-mess-up** [comment]
Most lag in tagpro is caused by the fact that it uses the TCP protocol which requires every packet to be confirmed. Thus, new packets do not get through until an old one has been confirmed. Web browsers use TCP, and without building a separate client, it is difficult to use UDP, where packets are unconfirmed.




In TagPro Next, there will be a standalone client that uses UDP, which will reduce lag.




It also looks like you might have some graphics freezing happening.

**Comment by ifactor1** [comment]
That happens like once every 10 minutes, the rest of the time it's perfect, no graphics issues steady 60.

I still see the rest of the players move around find, and looking in wireshark I can see all the other events firing after the dropped release event.
