### ISSUE TITLE
Refresh Respawn Delay is 15 seconds

### ISSUE THREAD

**Issue by MultiMediaWIll** [tagpro-game/tagpro-issues#37]
Some see this as way too long. Others see this as fixing an issue that doesn't exist.

**Comment by jufda** [comment]
I still think 5-10 seconds would be the optimal. If we could be sure that no conflicts between the game, browser and scripts happen, it wouldn't really matter how long it is as it shouldn't be necessary ever. We cannot be sure though, and I am sure almost all of the refreshing is done because black screen or something other bad happens, not to gain advantage by going fast to own base.

**Comment by Nick-Riggs** [comment]
It's 10 seconds.
